version = "3.8.1"
runner.dialect = scala213source3

# Максимальная длина строки
maxColumn = 100

# Отступы
indent.main = 2
indent.significant = 2

# Выравнивание
align.preset = more
align.tokens."+" = [
  { code = "=>",  owner = "Case" },
  { code = "%",   owner = "Term.ApplyInfix" },
  { code = "%%",  owner = "Term.ApplyInfix" },
  { code = "%%%", owner = "Term.ApplyInfix" },
  { code = ":=",  owner = "Term.ApplyInfix" },
  { code = "->",  owner = "Term.ApplyInfix" },
  { code = "<-",  owner = "Enumerator.Generator" },
  { code = "=",   owner = "(Def|Decl).(Var|Val)" }
]

# Переносы строк
newlines.source = keep
newlines.afterCurlyLambdaParams = squash
newlines.implicitParamListModifierPrefer = before

# Правила перезаписи (только те, что поддерживает Scalafmt)
rewrite.rules = [RedundantBraces, RedundantParens, PreferCurlyFors, SortModifiers]
rewrite.redundantBraces.stringInterpolation = true

# Trailing commas
trailingCommas = always

# Docstrings
docstrings.style = SpaceAsterisk
docstrings.wrap = no

# Spaces
spaces.inImportCurlyBraces = true
spaces.beforeContextBoundColon = Never
